### ISSUE TITLE
elementFromPoint may select parent element

### ISSUE THREAD

**Issue by bkrumnow** [droefs/HLISA#11]
```
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from HLISA.hlisa_action_chains import HLISA_ActionChains

driver = webdriver.Firefox()
driver.get("https://www.latercera.com")
time.sleep(5)
el = driver.find_element(By.CSS_SELECTOR, "article.aside:nth-child(22) > div:nth-child(1) > div:nth-child(1) > figure:nth-child(1) > a:nth-child(1)")
hlisa_click(driver, el)
driver.close()

def hlisa_click(driver, element):
    actions = HLISA_ActionChains(driver)
    actions.move_to_element_outside_viewport(element).click().perform()
    time.sleep(10)

```
It may be worth to re-evaluate how _elementFromPoint_ selects elements.

**Comment by bkrumnow** [comment]
Some thoughts on for the investigation:
* Does that happen in other browsers?
* How is the element build? Is much different to the others?

https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint states that ancestors can be selected if the element is anonymous or XBL generated content.

**Comment by droefs** [comment]
I cannot find the element using the CSS selector. Do you maybe have an id of it?

Looking through the page on anonymous content, I am getting more skeptical whether they use that: https://web.archive.org/web/20210119174123/https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XBL/XBL_1.0_Reference/Anonymous_Content

**Comment by bkrumnow** [comment]
Currently, I am unable to reproduce this case. All errors that I run into (with HLISA) would be addressed by #9. I am going for larger test run today. If nothing pops up, I would suggest to get #9 merged and close this one.

**Comment by droefs** [comment]
Yes I agree. It will be hard to debug this issue if it cannot be reproduced, given that the issue is already a strange phenomenon.

**Comment by bkrumnow** [comment]
As we do not find this any longer, I am going to close it. It can be re-opened if we run into it again.
