### ISSUE TITLE
Clicking place

### ISSUE THREAD

**Issue by zoiodelula** [droefs/HLISA#44]
Hello, I have a doubt, I would like to know if when we click on a button, HLISA always clicks in the same place or does it randomize the click within the button area?

**Comment by droefs** [comment]
Hi! HLISA does indeed randomize the click location within the button area. A click location in the middle of the button is more likely to occur than a click on the edges of the button.

**Comment by bkrumnow** [comment]
@zoiodelula: you could have a look at the [paper](https://doi.org/10.1145/3487552.3487843) (Sec. 4.1) which explains HLISA's approach to not release clicks at the same location.
